name: Telecom Intelligence Bot

permissions:
  contents: write

on:
  workflow_dispatch:

  schedule:
    - cron: "*/15 * * * *"

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Install Playwright
        run: |
          playwright install chromium
    
      - name: Show Main.py
        run: |
          echo "===== main.py ====="
          cat main.py

      - name: Run Bot
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          python main.py

      - name: Commit Updated Articles
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

          git add data/sent_articles.json

          git diff --cached --quiet || git commit -m "Update sent articles"

          git push

      - name: Upload Debug Files
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: opensignal-debug
          path: |
            opensignal.png
            opensignal.html
            dot.html
            dot.png
            opensignal_reports.html
            opensignal_reports.png
            speedtest.html
            speedtest.png
